---

galaxy_info:
  author: 'Bj√∏rn-Vegar Borge'
  description: 'Zscaler Internet Access - Check For Pending Configuration Changes'
  company: 'Netsecurity'

  license: 'GLWTPL'

  min_ansible_version: '2.1'

  galaxy_tags:
    - 'zscaler'
    - 'zia'
    - 'zscalerinternetaccess'
    - 'ztna'
    - 'zerotrustnetworkaccess'
    - 'security'

dependencies: []
